# Generated by Django 5.1.1 on 2024-10-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='document',
            field=models.FileField(default=None, upload_to='resources/'),
        ),
    ]
