# Generated by Django 5.1.1 on 2024-10-12 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boldpoint',
            name='item',
        ),
        migrations.RemoveField(
            model_name='bullet',
            name='item',
        ),
        migrations.RemoveField(
            model_name='categoryitem',
            name='service_line',
        ),
        migrations.RemoveField(
            model_name='furtherinfo',
            name='item',
        ),
        migrations.RemoveField(
            model_name='paragraphsection',
            name='item',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='SocialLink',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='user',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='author',
        ),
        migrations.DeleteModel(
            name='BoldPoint',
        ),
        migrations.DeleteModel(
            name='Bullet',
        ),
        migrations.DeleteModel(
            name='LineCategory',
        ),
        migrations.DeleteModel(
            name='FurtherInfo',
        ),
        migrations.DeleteModel(
            name='CategoryItem',
        ),
        migrations.DeleteModel(
            name='ParagraphSection',
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
