# Generated by Django 5.1.1 on 2024-10-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_sociallink_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linecategory',
            name='name',
            field=models.CharField(choices=[('Teachers & professionals', 'Teachers & professionals'), ('Parents & carers', 'Parents & carers'), ('4–11 year olds', '4–11 year olds'), ('11–18 year olds', '11–18 year olds')], max_length=100),
        ),
    ]
