# Generated by Django 5.1.1 on 2024-10-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_linecategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boldpoint',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='furtherinfo',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='paragraphsection',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
