# Generated by Django 5.1.1 on 2024-10-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='linecategory',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
