# Generated by Django 5.1.1 on 2024-10-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_boldpoint_item_alter_bullet_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='thread',
            name='cover_image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
