# Generated by Django 5.1.1 on 2024-10-13 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_subscriber_user_subscriber_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedToEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorized', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='subscriber',
            name='authorized_to_edit',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.authorizedtoedit'),
        ),
    ]
