# Generated by Django 5.1.1 on 2024-10-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_authorizedtoedit_subscriber_authorized_to_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='authorized_to_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AuthorizedToEdit',
        ),
    ]
